spring:
  
  profiles:
    include: db, redis, mail, oauth2

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      decorator:
        datasource:
          p6spy:
            enable-logging: true
      hibernate:
        hbm2ddl:
          auto: create
  
  thymeleaf:
    cache: false
    
server:
  port: 7070

jwt:
  secret-url: https://api-keymanager.cloud.toast.com/keymanager/v1.0/appkey/mcXcTmrnbRezlila/secrets/2e2391a7260646499390dc43b38a3cd0
  expire-time: 1800000 # 30분
  refresh-expire-time: 604800000 # 7일
