spring:
  
  profiles:
    include: jwt, db, redis

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      decorator:
        datasource:
          p6spy:
            enable-logging: true
  
  thymeleaf:
    cache: false
    
server:
  port: 7070
